### ISSUE TITLE
The aurora url should be able to be a zookeeper ensemble address

### ISSUE THREAD

**Issue by SEJeff** [tommyulfsparre/aurora_exporter#1]
That way when you have many schedulers in a HA configuration, it will find the current one.

**Comment by tommyulfsparre** [comment]
@SEJeff good idea. However, the aurora url doesn't have to point to a single scheduler it could be a DNS name with multiple A records (for all the schedulers). 

As zookeeper will always be present and DNS names might not be, I will add it.

**Comment by tommyulfsparre** [comment]
Should be fixed now!

**Comment by SEJeff** [comment]
Thanks!
