### ISSUE TITLE
SLA metrics per job

### ISSUE THREAD

**Issue by tommyulfsparre** [tommyulfsparre/aurora_exporter#2]
add sla metrics per job_key. The job_key should be extracted into Prometheus labels.

**Comment by StephanErb** [comment]
I will look into this

**Comment by tommyulfsparre** [comment]
@StephanErb Thanks! 
You can look at [labled-vars](https://github.com/tommyulfsparre/aurora_exporter/tree/labled-vars) where I extract some labels on a set of metrics

**Comment by tommyulfsparre** [comment]
I merged [labled-vars](https://github.com/tommyulfsparre/aurora_exporter/tree/labled-vars) but will gladly accept a PR for a different implementation.  Closing this for now.
